In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [2]:
main_df=pd.read_csv('https://breathecode.herokuapp.com/asset/internal-link?id=435&path=url_spam.csv')

In [3]:
main_df.head()

url  is_spam
0  https://briefingday.us8.list-manage.com/unsubs...     True
1                             https://www.hvper.com/     True
2                 https://briefingday.com/m/v4n3i4f3     True
3   https://briefingday.com/n/20200618/m#commentform    False
4                        https://briefingday.com/fan     True

In [4]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   url      2999 non-null   object
 1   is_spam  2999 non-null   bool  
dtypes: bool(1), object(1)
memory usage: 26.5+ KB


In [5]:
main_df['url'].value_counts()

url
https://www.bloomberg.com/tosv2.html                                                                 26
https://briefingday.us8.list-manage.com/unsubscribe                                                  13
https://www.hvper.com/                                                                               13
https://briefingday.com/fan                                                                          13
https://briefingday.com/m/v4n3i4f3                                                                   13
                                                                                                     ..
https://www.forecastapp.net/                                                                          1
https://www.imperica.com/en/newsletter                                                                1
https://www.youtube.com/watch?v=OqRWb9JQW_0                                                           1
https://www.youtube.com/watch?v=5kCGA2snGL8                 

In [6]:
main_df.isna().sum()

url        0
is_spam    0
dtype: int64

In [7]:
main_df['url'] = main_df['url'].str.strip().str.lower()

In [8]:
main_df['url']

0       https://briefingday.us8.list-manage.com/unsubs...
1                                  https://www.hvper.com/
2                      https://briefingday.com/m/v4n3i4f3
3        https://briefingday.com/n/20200618/m#commentform
4                             https://briefingday.com/fan
                              ...                        
2994    https://www.smartcitiesworld.net/news/news/dee...
2995                        https://www.youtube.com/watch
2996    https://techcrunch.com/2019/07/04/an-optimisti...
2997    https://www.technologyreview.com/2019/12/20/13...
2998         https://www.bbc.com/news/technology-51018758
Name: url, Length: 2999, dtype: object

In [9]:
main_df['is_spam']

0        True
1        True
2        True
3       False
4        True
        ...  
2994    False
2995     True
2996    False
2997    False
2998    False
Name: is_spam, Length: 2999, dtype: bool

In [10]:
main_df['is_spam'] = main_df['is_spam'].map({True:1,False:0})

In [11]:
main_df['is_spam']

0       1
1       1
2       1
3       0
4       1
       ..
2994    0
2995    1
2996    0
2997    0
2998    0
Name: is_spam, Length: 2999, dtype: int64

In [12]:
main_df['url']=main_df['url'].astype(str).apply(lambda x: re.sub(r'\s+',' ',x))

In [13]:
main_df['url']

0       https://briefingday.us8.list-manage.com/unsubs...
1                                  https://www.hvper.com/
2                      https://briefingday.com/m/v4n3i4f3
3        https://briefingday.com/n/20200618/m#commentform
4                             https://briefingday.com/fan
                              ...                        
2994    https://www.smartcitiesworld.net/news/news/dee...
2995                        https://www.youtube.com/watch
2996    https://techcrunch.com/2019/07/04/an-optimisti...
2997    https://www.technologyreview.com/2019/12/20/13...
2998         https://www.bbc.com/news/technology-51018758
Name: url, Length: 2999, dtype: object

In [14]:
re.sub('[.,?!?*&"\']',' ',main_df['url'][0])


'https://briefingday us8 list-manage com/unsubscribe'

In [15]:
main_df['url']=main_df['url'].astype(str).apply(lambda x: re.sub(r'[.,?!*&"\' ]', '', x))

In [16]:
main_df['url']

0        https://briefingdayus8list-managecom/unsubscribe
1                                    https://wwwhvpercom/
2                       https://briefingdaycom/m/v4n3i4f3
3         https://briefingdaycom/n/20200618/m#commentform
4                              https://briefingdaycom/fan
                              ...                        
2994    https://wwwsmartcitiesworldnet/news/news/deepf...
2995                          https://wwwyoutubecom/watch
2996    https://techcrunchcom/2019/07/04/an-optimistic...
2997    https://wwwtechnologyreviewcom/2019/12/20/1314...
2998           https://wwwbbccom/news/technology-51018758
Name: url, Length: 2999, dtype: object

In [17]:
x=main_df['url']
y= main_df['is_spam']
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [18]:
x_train

2895               https://accountsgooglecom/servicelogin
2291    https://wwwespncom/nfl/story/_/id/29383371/net...
2554    https://wwwreuterscom/article/us-pakistan-atta...
401     https://theconversationcom/journalists-believe...
2406    https://wwwmorningbrewcom/daily/stories/2020/0...
                              ...                        
933     https://wwwncbinlmnihgov/pmc/articles/pmc5972398/
726     https://wwwbbccom/worklife/article/20200622-ho...
319     https://wwwtheguardiancom/world/2020/jun/29/co...
1171                            https://readtheplaquecom/
1554    http://wwwtodayifoundoutcom/indexphp/2020/06/c...
Name: url, Length: 2249, dtype: object

In [19]:
x_test

260     https://wwwellecom/culture/movies-tv/g32644924...
1495    https://wwwnewyorkercom/news/news-desk/can-dom...
58      https://wwwreuterscom/article/us-usa-trump-imm...
2248                 https://wwwyoutubecom/user/voxdotcom
732     https://wwwthesunmagazineorg/issues/535/out-of...
                              ...                        
2871        https://gimletmediacom/shows/reply-all/o2hx34
2882    https://wwwefforg/deeplinks/2020/06/inside-inv...
1083                            https://bringcamphomecom/
2385    https://wwwcnbccom/2020/06/29/new-york-citys-b...
242     https://ourworldindataorg/grapher/daily-covid-...
Name: url, Length: 750, dtype: object

In [20]:
y_train

2895    1
2291    0
2554    0
401     0
2406    0
       ..
933     0
726     0
319     0
1171    0
1554    0
Name: is_spam, Length: 2249, dtype: int64

In [21]:
y_test

260     0
1495    0
58      0
2248    1
732     0
       ..
2871    0
2882    0
1083    0
2385    0
242     1
Name: is_spam, Length: 750, dtype: int64

In [22]:
vec_model = CountVectorizer(stop_words='english')
#Scikit-learn’in hazır İngilizce stop word listesini al
#ve bu kelimeleri vektörleştirme sırasında tamamen görmezden gel
#Yani model “the”, “is”, “and” gibi kelimeleri hiç feature yapmaz.

In [23]:
vec_model

CountVectorizer(stop_words='english')

In [24]:
x

0        https://briefingdayus8list-managecom/unsubscribe
1                                    https://wwwhvpercom/
2                       https://briefingdaycom/m/v4n3i4f3
3         https://briefingdaycom/n/20200618/m#commentform
4                              https://briefingdaycom/fan
                              ...                        
2994    https://wwwsmartcitiesworldnet/news/news/deepf...
2995                          https://wwwyoutubecom/watch
2996    https://techcrunchcom/2019/07/04/an-optimistic...
2997    https://wwwtechnologyreviewcom/2019/12/20/1314...
2998           https://wwwbbccom/news/technology-51018758
Name: url, Length: 2999, dtype: object

In [25]:
x_train_vec=vec_model.fit_transform(x_train).toarray()

In [26]:
pd.DataFrame(x_train_vec)

0     1     2     3     4     5     6     7     8     9     ...  5755  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2244     0     0     0     0     0     0     0     0     0     0  ...     0   
2245     0     0     0     0     0     0     0     0     0     0  ...     0   
2246     0     0     0     0     0     0     0     0     0     0  ...     0   
2247     0     0     0     0     0     0     0     0     0     0  ...     0   
2248     0     0     0     0     0     0     0     0     0     0  ...     0   

      5756  5757  5758  5759  5760  5761  5762  5763  5764  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2244     0     0     0     0     0     0     0     0     0  
2245     0     0     0     0     0     0     0     0     0  
2246     0     0     0     0     0     0     0     0     0  
2247     0     0     0     0     0     0     0     0     0  
2248     0     0     0     0     0     0     0     0     0  

[2249 rows x 5765 columns]

In [27]:
x_test_vec= vec_model.transform(x_test).toarray()

In [28]:
pd.DataFrame(x_test_vec)

0     1     2     3     4     5     6     7     8     9     ...  5755  \
0       0     0     0     0     0     0     0     0     0     0  ...     0   
1       0     0     0     0     0     0     0     0     0     0  ...     0   
2       0     0     0     0     0     0     0     0     0     0  ...     0   
3       0     0     0     0     0     0     0     0     0     0  ...     0   
4       0     0     0     0     0     0     0     0     0     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
745     0     0     0     0     0     0     0     0     0     0  ...     0   
746     0     0     0     0     0     0     0     0     0     0  ...     0   
747     0     0     0     0     0     0     0     0     0     0  ...     0   
748     0     0     0     0     0     0     0     0     0     0  ...     0   
749     0     0     0     0     0     0     0     0     0     0  ...     0   

     5756  5757  5758  5759  5760  5761  5762  5763  5764  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
745     0     0     0     0     0     0     0     0     0  
746     0     0     0     0     0     0     0     0     0  
747     0     0     0     0     0     0     0     0     0  
748     0     0     0     0     0     0     0     0     0  
749     0     0     0     0     0     0     0     0     0  

[750 rows x 5765 columns]

In [29]:
x_train_vec.max()

np.int64(2)

In [30]:
#“Since the features represent word counts, Multinomial Naive Bayes and bernoulli was  used.”
#MULTINOMIAL NE DEMEK?
#Multinomial şunu bilir:
#“Bir şey kaç kere oldu?”
#BERNOULLI = VAR / YOK
#Şunu yapıyorsan:
#“Bu kelime var mı?”
# GAUSSIAN = ÖLÇÜYORUM

In [31]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [32]:
gnb_model = GaussianNB()
gnb_model.fit(x_train_vec,y_train)

GaussianNB()

In [33]:
train_preds_gauss =  gnb_model.predict(x_train_vec)
test_preds_gauss = gnb_model.predict(x_test_vec)

In [34]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [36]:
print('GAUSSIAN NAIVE BAYES ON THE TRAINING DATA ')
print(f'confussion matrix :\n {confusion_matrix(y_true=y_train,y_pred=train_preds_gauss)}')
print(f'accuracy_score : \n {accuracy_score(y_true=y_train,y_pred=train_preds_gauss)}')
print(f'classification_report : \n {classification_report(y_true= y_train,y_pred=train_preds_gauss)}')

GAUSSIAN NAIVE BAYES ON THE TRAINING DATA 
confussion matrix :
 [[1723    1]
 [   0  525]]
accuracy_score : 
 0.9995553579368608
classification_report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1724
           1       1.00      1.00      1.00       525

    accuracy                           1.00      2249
   macro avg       1.00      1.00      1.00      2249
weighted avg       1.00      1.00      1.00      2249



In [37]:
print('GAUSSIAN NAIVE BAYES ON THE TESTING DATA ')
print(f'confussion matrix :\n {confusion_matrix(y_true=y_test,y_pred=test_preds_gauss)}')
print(f'accuracy_score : \n {accuracy_score(y_true=y_test,y_pred=test_preds_gauss)}')
print(f'classification_report : \n {classification_report(y_true= y_test,y_pred=test_preds_gauss)}')

GAUSSIAN NAIVE BAYES ON THE TESTING DATA 
confussion matrix :
 [[525  54]
 [ 11 160]]
accuracy_score : 
 0.9133333333333333
classification_report : 
               precision    recall  f1-score   support

           0       0.98      0.91      0.94       579
           1       0.75      0.94      0.83       171

    accuracy                           0.91       750
   macro avg       0.86      0.92      0.89       750
weighted avg       0.93      0.91      0.92       750



In [38]:
multinomia = MultinomialNB()
multinomia.fit(x_train_vec,y_train)

MultinomialNB()

In [39]:
train_preds_multi = multinomia.predict(x_train_vec)
test_preds_multi = multinomia.predict(x_test_vec)

In [40]:
print('MultinomialNB NAIVE BAYES ON THE TRAINING DATA ')
print(f'confussion matrix :\n {confusion_matrix(y_true=y_train,y_pred=train_preds_multi)}')
print(f'accuracy_score : \n {accuracy_score(y_true=y_train,y_pred=train_preds_multi)}')
print(f'classification_report : \n {classification_report(y_true= y_train,y_pred=train_preds_multi)}')

MultinomialNB NAIVE BAYES ON THE TRAINING DATA 
confussion matrix :
 [[1680   44]
 [  48  477]]
accuracy_score : 
 0.9590929301911961
classification_report : 
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1724
           1       0.92      0.91      0.91       525

    accuracy                           0.96      2249
   macro avg       0.94      0.94      0.94      2249
weighted avg       0.96      0.96      0.96      2249



In [41]:
print('MultinomialNB NAIVE BAYES ON THE TESTING DATA ')
print(f'confussion matrix :\n {confusion_matrix(y_true=y_test,y_pred=test_preds_multi)}')
print(f'accuracy_score : \n {accuracy_score(y_true=y_test,y_pred=test_preds_multi)}')
print(f'classification_report : \n {classification_report(y_true= y_test,y_pred=test_preds_multi)}')

MultinomialNB NAIVE BAYES ON THE TESTING DATA 
confussion matrix :
 [[565  14]
 [ 33 138]]
accuracy_score : 
 0.9373333333333334
classification_report : 
               precision    recall  f1-score   support

           0       0.94      0.98      0.96       579
           1       0.91      0.81      0.85       171

    accuracy                           0.94       750
   macro avg       0.93      0.89      0.91       750
weighted avg       0.94      0.94      0.94       750

